"""The strategy foundry boundary: what a candidate strategy is, and what it took to get there."""

from trading_house.research.backtest.mark import (
    MAX_EQUITY_OBSERVATIONS,
    BacktestOutcome,
    EquityObservation,
    EquitySeries,
    derive_daily_returns,
)
from trading_house.research.canonical import canonical_bytes, canonical_sha256
from trading_house.research.evidence import (
    CostSummary,
    DailyReturnPoint,
    EvidenceBundle,
    EvidenceProvenance,
    EvidenceStore,
    StoredEvidence,
)
from trading_house.research.packages import PromotionStage, StrategyPackage, StrategySpec
from trading_house.research.trial_ledger import (
    CostAttributionStatus,
    HoldoutState,
    LedgerEvent,
    LedgerEventType,
    LedgerIntegrityReport,
    LedgerRecord,
    RegistrationState,
    ReturnSeriesBasis,
    ScopeKind,
    Trial,
    TrialCounters,
    TrialLedger,
    TrialProtocol,
    TrialSpec,
    TrialStatus,
    deflation_trial_count,
    trial_counters,
)

__all__ = [
    "MAX_EQUITY_OBSERVATIONS",
    "BacktestOutcome",
    "CostAttributionStatus",
    "CostSummary",
    "DailyReturnPoint",
    "EquityObservation",
    "EquitySeries",
    "EvidenceBundle",
    "EvidenceProvenance",
    "EvidenceStore",
    "HoldoutState",
    "LedgerEvent",
    "LedgerEventType",
    "LedgerIntegrityReport",
    "LedgerRecord",
    "PromotionStage",
    "RegistrationState",
    "ReturnSeriesBasis",
    "ScopeKind",
    "StoredEvidence",
    "StrategyPackage",
    "StrategySpec",
    "Trial",
    "TrialCounters",
    "TrialLedger",
    "TrialProtocol",
    "TrialSpec",
    "TrialStatus",
    "canonical_bytes",
    "canonical_sha256",
    "deflation_trial_count",
    "derive_daily_returns",
    "trial_counters",
]
